/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:466155cb-ff83-4623-99d1-947fc1eba919",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_lX4nMcPZC",
    "aws_user_pools_web_client_id": "1jctj1jm78gjd72m25qs2ouin0",
    "oauth": {}
};


export default awsmobile;
